services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - BASE_URL=${BASE_URL}  # Pass BASE_URL to the Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
