services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
